-- =============================================================================
-- seed.sql — dane startowe: kategorie HVAC, atrybuty, dostawa, grupy klientów,
-- marże, hurtownie, strony statyczne, produkty demo (z ofertami hurtowni mock).
-- Idempotentny (on conflict do nothing / update).
-- =============================================================================

-- --- Grupy klientów ---
insert into public.customer_groups (code, name, discount_pct, price_mode) values
  ('b2c', 'Klient indywidualny', 0, 'gross'),
  ('b2b_standard', 'Instalator B2B', 5, 'net'),
  ('b2b_vip', 'Instalator B2B VIP', 10, 'net')
on conflict (code) do nothing;

-- --- Hurtownie ---
insert into public.suppliers (code, name, feed_type, feed_config, active, priority, sync_interval_min, last_sync_status) values
  ('mock', 'Hurtownia demo (mock)', 'manual', '{"auto_create_products": true}'::jsonb, true, 900, 60, null),
  ('iglocar', 'Igłocar', 'manual', '{"auto_create_products": false}'::jsonb, false, 10, 60, 'not_configured'),
  ('autoklima', 'Autoklima', 'manual', '{"auto_create_products": false}'::jsonb, false, 20, 60, 'not_configured'),
  ('kaisai', 'KAISAI', 'manual', '{"auto_create_products": false}'::jsonb, false, 30, 60, 'not_configured'),
  ('termosilesia', 'Termosilesia', 'manual', '{"auto_create_products": false}'::jsonb, false, 40, 60, 'not_configured'),
  ('sinclair', 'Sinclair', 'manual', '{"auto_create_products": false}'::jsonb, false, 50, 60, 'not_configured')
on conflict (code) do nothing;

-- --- Reguły marż ---
insert into public.margin_rules (name, scope, scope_id, margin_pct, min_margin_cents, priority, active)
select 'Marża globalna 18%', 'global', null, 18, 500, 0, true
where not exists (select 1 from public.margin_rules where scope = 'global');

-- --- Metody dostawy ---
insert into public.shipping_methods (code, name, carrier, description, price_net_cents, free_from_cents, free_from_cents_b2b, max_weight_kg, pallet, pickup, active, position) values
  ('courier_dpd', 'Kurier DPD', 'DPD', 'Dostawa 1–2 dni robocze, paczki do 30 kg', 1990, 150000, 200000, 30, false, false, true, 10),
  ('courier_inpost', 'Kurier InPost', 'InPost', 'Dostawa 1–2 dni robocze, paczki do 25 kg', 1690, 150000, 200000, 25, false, false, true, 20),
  ('pallet', 'Dostawa paletowa', 'Raben', 'Przesyłka paletowa 2–4 dni robocze, rozładunek na burcie auta', 19900, null, 500000, null, true, false, true, 30),
  ('pallet_lift', 'Dostawa paletowa z windą', 'Raben', 'Przesyłka paletowa z autem z windą i rozładunkiem pod adres', 24900, null, null, null, true, false, true, 40),
  ('pickup', 'Odbiór osobisty', null, 'Odbiór w magazynie po potwierdzeniu dostępności', 0, null, null, null, false, true, true, 50)
on conflict (code) do nothing;

-- --- Kategorie (3 poziomy) ---
insert into public.categories (slug, name, parent_id, position, seo_title, seo_description) values
  ('klimatyzacja', 'Klimatyzacja', null, 10, 'Klimatyzatory — split, multi-split, kasetonowe | Sklep HVAC', 'Klimatyzatory ścienne, multi-split, kasetonowe, kanałowe i przenośne. Ceny B2C i B2B, dostawa paletowa.'),
  ('pompy-ciepla', 'Pompy ciepła', null, 20, 'Pompy ciepła powietrze-woda, monoblok, split, CWU | Sklep HVAC', 'Pompy ciepła monoblok i split, pompy do CWU. Doradztwo doboru, dostawa paletowa.'),
  ('wentylacja-i-rekuperacja', 'Wentylacja i rekuperacja', null, 30, 'Rekuperacja i wentylacja | Sklep HVAC', 'Rekuperatory, wentylatory, kanały i kształtki wentylacyjne.'),
  ('czynniki-i-narzedzia', 'Czynniki i narzędzia', null, 40, 'Czynniki chłodnicze i narzędzia serwisowe | Sklep HVAC', 'Czynniki R32, R410A, pompy próżniowe, manometry, wagi, kielicharki.'),
  ('akcesoria-montazowe', 'Akcesoria montażowe', null, 50, 'Akcesoria montażowe do klimatyzacji | Sklep HVAC', 'Rury miedziane, wsporniki, pompki skroplin, kable, izolacje.'),
  ('serwis-i-czesci', 'Serwis i części', null, 60, 'Części serwisowe do klimatyzacji | Sklep HVAC', 'Filtry, piloty, płytki sterujące i czujniki.')
on conflict (slug) do nothing;

insert into public.categories (slug, name, parent_id, position) values
  ('klimatyzatory-split', 'Klimatyzatory split', (select id from public.categories where slug = 'klimatyzacja'), 10),
  ('multi-split', 'Multi-split', (select id from public.categories where slug = 'klimatyzacja'), 20),
  ('kasetonowe', 'Kasetonowe', (select id from public.categories where slug = 'klimatyzacja'), 30),
  ('kanalowe', 'Kanałowe', (select id from public.categories where slug = 'klimatyzacja'), 40),
  ('przenosne', 'Przenośne', (select id from public.categories where slug = 'klimatyzacja'), 50),
  ('powietrze-woda', 'Powietrze-woda', (select id from public.categories where slug = 'pompy-ciepla'), 10),
  ('cwu', 'Pompy ciepła do CWU', (select id from public.categories where slug = 'pompy-ciepla'), 40),
  ('rekuperatory', 'Rekuperatory', (select id from public.categories where slug = 'wentylacja-i-rekuperacja'), 10),
  ('wentylatory', 'Wentylatory', (select id from public.categories where slug = 'wentylacja-i-rekuperacja'), 20),
  ('kanaly-i-ksztaltki', 'Kanały i kształtki', (select id from public.categories where slug = 'wentylacja-i-rekuperacja'), 30),
  ('czynniki-chlodnicze', 'Czynniki chłodnicze', (select id from public.categories where slug = 'czynniki-i-narzedzia'), 10),
  ('narzedzia', 'Narzędzia serwisowe', (select id from public.categories where slug = 'czynniki-i-narzedzia'), 20),
  ('manometry-i-pompy-prozniowe', 'Manometry i pompy próżniowe', (select id from public.categories where slug = 'czynniki-i-narzedzia'), 30),
  ('rury-miedziane', 'Rury miedziane', (select id from public.categories where slug = 'akcesoria-montazowe'), 10),
  ('wsporniki', 'Wsporniki i podstawy', (select id from public.categories where slug = 'akcesoria-montazowe'), 20),
  ('pompki-skroplin', 'Pompki skroplin', (select id from public.categories where slug = 'akcesoria-montazowe'), 30),
  ('kable-i-przewody', 'Kable i przewody', (select id from public.categories where slug = 'akcesoria-montazowe'), 40),
  ('izolacje', 'Izolacje i węże', (select id from public.categories where slug = 'akcesoria-montazowe'), 50),
  ('filtry', 'Filtry', (select id from public.categories where slug = 'serwis-i-czesci'), 10),
  ('piloty', 'Piloty', (select id from public.categories where slug = 'serwis-i-czesci'), 20),
  ('plytki-i-czujniki', 'Płytki i czujniki', (select id from public.categories where slug = 'serwis-i-czesci'), 30)
on conflict (slug) do nothing;

-- poziom 3: pompy ciepła powietrze-woda → monoblok / split
insert into public.categories (slug, name, parent_id, position) values
  ('monoblok', 'Monoblok', (select id from public.categories where slug = 'powietrze-woda'), 10),
  ('pompy-split', 'Split', (select id from public.categories where slug = 'powietrze-woda'), 20)
on conflict (slug) do nothing;

-- --- Definicje atrybutów (filtry techniczne) ---
insert into public.product_attributes_def (key, label, unit, type, filterable, category_ids, position) values
  ('typ', 'Typ', null, 'select', true, '{}', 10),
  ('moc_chlodnicza_kw', 'Moc chłodnicza', 'kW', 'number', true, '{}', 20),
  ('moc_grzewcza_kw', 'Moc grzewcza', 'kW', 'number', true, '{}', 30),
  ('powierzchnia_m2', 'Powierzchnia pomieszczenia', 'm²', 'number', true, '{}', 35),
  ('klasa_energetyczna_chlodzenie', 'Klasa energetyczna (chłodzenie)', null, 'select', true, '{}', 40),
  ('klasa_energetyczna_grzanie', 'Klasa energetyczna (grzanie)', null, 'select', true, '{}', 50),
  ('czynnik', 'Czynnik chłodniczy', null, 'select', true, '{}', 60),
  ('zasilanie', 'Zasilanie', null, 'select', true, '{}', 70),
  ('seer', 'SEER', null, 'number', false, '{}', 80),
  ('scop', 'SCOP', null, 'number', false, '{}', 90),
  ('poziom_halasu_db', 'Poziom hałasu (jedn. wewn.)', 'dB(A)', 'number', true, '{}', 100),
  ('wifi', 'Sterowanie Wi‑Fi', null, 'boolean', true, '{}', 110),
  ('liczba_jednostek', 'Liczba jednostek wewnętrznych', null, 'number', true, '{}', 120),
  ('temp_zasilania_max_c', 'Maks. temp. zasilania', '°C', 'number', false, '{}', 130),
  ('pojemnosc_l', 'Pojemność zbiornika', 'l', 'number', true, '{}', 140),
  ('wydajnosc_m3h', 'Wydajność', 'm³/h', 'number', true, '{}', 150),
  ('odzysk_ciepla_pct', 'Odzysk ciepła', '%', 'number', false, '{}', 160),
  ('srednica_mm', 'Średnica', 'mm', 'number', true, '{}', 170),
  ('srednica_cal', 'Średnica', 'cal', 'select', true, '{}', 175),
  ('dlugosc_m', 'Długość', 'm', 'number', true, '{}', 180),
  ('dlugosc_mm', 'Długość', 'mm', 'number', false, '{}', 185),
  ('pojemnosc_kg', 'Pojemność butli', 'kg', 'number', true, '{}', 190),
  ('udzwig_kg', 'Udźwig', 'kg', 'number', false, '{}', 200),
  ('izolacja', 'Izolacja', null, 'text', false, '{}', 210),
  ('spręż_pa', 'Spręż dyspozycyjny', 'Pa', 'number', false, '{}', 220),
  ('wydajnosc_lh', 'Wydajność pompki', 'l/h', 'number', false, '{}', 230),
  ('podnoszenie_m', 'Wysokość podnoszenia', 'm', 'number', false, '{}', 240),
  ('przekroj_mm2', 'Przekrój żyły', 'mm²', 'number', false, '{}', 250),
  ('liczba_zyl', 'Liczba żył', null, 'number', false, '{}', 260),
  ('grubosc_mm', 'Grubość', 'mm', 'number', false, '{}', 270),
  ('pasuje_do', 'Pasuje do', null, 'text', false, '{}', 280),
  ('zakres', 'Zakres', null, 'text', false, '{}', 290),
  ('wydajnosc_lmin', 'Wydajność pompy', 'l/min', 'number', false, '{}', 300)
on conflict (key) do nothing;

-- --- Strony statyczne ---
insert into public.static_pages (slug, title, content_html, published, position) values
  ('regulamin', 'Regulamin sklepu', '<h2>§1 Postanowienia ogólne</h2><p>Niniejszy regulamin określa zasady składania zamówień i zawierania umów sprzedaży w sklepie internetowym.</p><p><em>TODO(ustalić): pełna treść regulaminu od klienta (dane sprzedawcy, reklamacje, odstąpienie od umowy).</em></p>', true, 10),
  ('polityka-prywatnosci', 'Polityka prywatności', '<h2>Administrator danych</h2><p>Administratorem danych osobowych jest właściciel sklepu. Dane przetwarzane są w celu realizacji zamówień, prowadzenia konta klienta i obsługi reklamacji.</p><h2>Pliki cookies</h2><p>Sklep używa plików cookies niezbędnych do działania oraz, za zgodą, analitycznych i marketingowych. Zgodę można zmienić w każdej chwili w ustawieniach cookies.</p><p><em>TODO(ustalić): dane administratora i inspektora ochrony danych.</em></p>', true, 20),
  ('dostawa-i-platnosc', 'Dostawa i płatność', '<h2>Dostawa</h2><ul><li><strong>Kurier</strong> (DPD / InPost) — paczki do 30 kg, 1–2 dni robocze.</li><li><strong>Dostawa paletowa</strong> — klimatyzatory kasetonowe, kanałowe, pompy ciepła, rekuperatory oraz zamówienia powyżej 30 kg. 2–4 dni robocze.</li><li><strong>Odbiór osobisty</strong> — po potwierdzeniu dostępności towaru.</li></ul><h2>Płatność</h2><ul><li><strong>Przelew tradycyjny / proforma</strong> — numer konta i tytuł przelewu otrzymasz w e-mailu z potwierdzeniem zamówienia.</li><li><strong>Płatność odroczona 14 dni</strong> — dla zweryfikowanych klientów B2B.</li></ul><p><em>TODO(ustalić): płatności online (Przelewy24 / PayU / Tpay).</em></p>', true, 30),
  ('kontakt', 'Kontakt', '<p>Masz pytania o dobór urządzenia lub zamówienie? Napisz lub zadzwoń — doradzamy instalatorom i klientom indywidualnym.</p><p><em>TODO(ustalić): dane kontaktowe sklepu (telefon, e-mail, adres magazynu, godziny pracy).</em></p>', true, 40),
  ('o-nas', 'O nas', '<p>Jesteśmy sklepem specjalistycznym dla branży HVAC. Oferujemy klimatyzatory, pompy ciepła, systemy rekuperacji oraz pełne zaplecze montażowe i serwisowe, z dostawą paletową i obsługą B2B.</p><p><em>TODO(ustalić): treść od klienta.</em></p>', true, 50)
on conflict (slug) do nothing;

-- --- Marki ---
insert into public.brands (slug, name) values
  ('armacell', 'Armacell'),
  ('aspen', 'Aspen'),
  ('elektrokabel', 'Elektrokabel'),
  ('gree', 'Gree'),
  ('honeywell', 'Honeywell'),
  ('kaisai', 'KAISAI'),
  ('midea', 'Midea'),
  ('rawicom', 'Rawicom'),
  ('refco', 'Refco'),
  ('rotenso', 'Rotenso'),
  ('sinclair', 'Sinclair'),
  ('vents', 'Vents')
on conflict (slug) do nothing;

-- --- Produkty demo (30+) — mapowane do ofert hurtowni mock po EAN/SKU ---
insert into public.products (sku, slug, name, ean, brand_id, category_id, description_html, attributes, images, documents, weight_kg, pallet_required, status, featured) values
  ('KAI-KEX-26', 'klimatyzator-scienny-kaisai-eco-kex-2-6-kw', 'Klimatyzator ścienny KAISAI Eco KEX 2.6 kW', '5900000000015', (select id from public.brands where slug = 'kaisai'), (select id from public.categories where slug = 'klimatyzatory-split'), '<p>Zestaw klimatyzacji ściennej KAISAI Eco KEX o mocy chłodniczej 2.6 kW (jednostka wewnętrzna + zewnętrzna). Czynnik R32, sprężarka inwerterowa, tryb grzania do -15°C, sterowanie Wi‑Fi w standardzie. Zalecany do pomieszczeń do ok. 26 m².</p><ul><li>Filtr antybakteryjny</li><li>Funkcja I Feel</li><li>Timer 24h</li><li>5 lat gwarancji po rejestracji</li></ul>', '{"typ": "ścienny", "moc_chlodnicza_kw": 2.6, "moc_grzewcza_kw": 2.9, "czynnik": "R32", "klasa_energetyczna_chlodzenie": "A++", "klasa_energetyczna_grzanie": "A+", "seer": 6.4, "scop": 4.0, "poziom_halasu_db": 22, "zasilanie": "1-fazowe", "wifi": true, "powierzchnia_m2": 26}'::jsonb, array['https://placehold.co/800x800/F8FAFC/0F172A?text=KAI-KEX-26'], '[{"name": "Karta katalogowa", "url": "https://example.com/docs/KAI-KEX-26.pdf", "type": "karta"}]'::jsonb, 43.72, false, 'active', false),
  ('KAI-KEX-35', 'klimatyzator-scienny-kaisai-eco-kex-3-5-kw', 'Klimatyzator ścienny KAISAI Eco KEX 3.5 kW', '5900000000022', (select id from public.brands where slug = 'kaisai'), (select id from public.categories where slug = 'klimatyzatory-split'), '<p>Zestaw klimatyzacji ściennej KAISAI Eco KEX o mocy chłodniczej 3.5 kW (jednostka wewnętrzna + zewnętrzna). Czynnik R32, sprężarka inwerterowa, tryb grzania do -15°C, sterowanie Wi‑Fi w standardzie. Zalecany do pomieszczeń do ok. 35 m².</p><ul><li>Filtr antybakteryjny</li><li>Funkcja I Feel</li><li>Timer 24h</li><li>5 lat gwarancji po rejestracji</li></ul>', '{"typ": "ścienny", "moc_chlodnicza_kw": 3.5, "moc_grzewcza_kw": 3.8, "czynnik": "R32", "klasa_energetyczna_chlodzenie": "A++", "klasa_energetyczna_grzanie": "A+", "seer": 6.4, "scop": 4.0, "poziom_halasu_db": 23, "zasilanie": "1-fazowe", "wifi": true, "powierzchnia_m2": 35}'::jsonb, array['https://placehold.co/800x800/F8FAFC/0F172A?text=KAI-KEX-35'], '[{"name": "Karta katalogowa", "url": "https://example.com/docs/KAI-KEX-35.pdf", "type": "karta"}]'::jsonb, 45.7, false, 'active', true),
  ('KAI-KEX-53', 'klimatyzator-scienny-kaisai-eco-kex-5-3-kw', 'Klimatyzator ścienny KAISAI Eco KEX 5.3 kW', '5900000000039', (select id from public.brands where slug = 'kaisai'), (select id from public.categories where slug = 'klimatyzatory-split'), '<p>Zestaw klimatyzacji ściennej KAISAI Eco KEX o mocy chłodniczej 5.3 kW (jednostka wewnętrzna + zewnętrzna). Czynnik R32, sprężarka inwerterowa, tryb grzania do -15°C, sterowanie Wi‑Fi w standardzie. Zalecany do pomieszczeń do ok. 53 m².</p><ul><li>Filtr antybakteryjny</li><li>Funkcja I Feel</li><li>Timer 24h</li><li>5 lat gwarancji po rejestracji</li></ul>', '{"typ": "ścienny", "moc_chlodnicza_kw": 5.3, "moc_grzewcza_kw": 5.6, "czynnik": "R32", "klasa_energetyczna_chlodzenie": "A++", "klasa_energetyczna_grzanie": "A+", "seer": 6.4, "scop": 4.0, "poziom_halasu_db": 24, "zasilanie": "1-fazowe", "wifi": true, "powierzchnia_m2": 53}'::jsonb, array['https://placehold.co/800x800/F8FAFC/0F172A?text=KAI-KEX-53'], '[{"name": "Karta katalogowa", "url": "https://example.com/docs/KAI-KEX-53.pdf", "type": "karta"}]'::jsonb, 49.66, false, 'active', false),
  ('KAI-KEX-70', 'klimatyzator-scienny-kaisai-eco-kex-7-0-kw', 'Klimatyzator ścienny KAISAI Eco KEX 7.0 kW', '5900000000046', (select id from public.brands where slug = 'kaisai'), (select id from public.categories where slug = 'klimatyzatory-split'), '<p>Zestaw klimatyzacji ściennej KAISAI Eco KEX o mocy chłodniczej 7.0 kW (jednostka wewnętrzna + zewnętrzna). Czynnik R32, sprężarka inwerterowa, tryb grzania do -15°C, sterowanie Wi‑Fi w standardzie. Zalecany do pomieszczeń do ok. 70 m².</p><ul><li>Filtr antybakteryjny</li><li>Funkcja I Feel</li><li>Timer 24h</li><li>5 lat gwarancji po rejestracji</li></ul>', '{"typ": "ścienny", "moc_chlodnicza_kw": 7.0, "moc_grzewcza_kw": 7.3, "czynnik": "R32", "klasa_energetyczna_chlodzenie": "A++", "klasa_energetyczna_grzanie": "A+", "seer": 6.4, "scop": 4.0, "poziom_halasu_db": 25, "zasilanie": "1-fazowe", "wifi": true, "powierzchnia_m2": 70}'::jsonb, array['https://placehold.co/800x800/F8FAFC/0F172A?text=KAI-KEX-70'], '[{"name": "Karta katalogowa", "url": "https://example.com/docs/KAI-KEX-70.pdf", "type": "karta"}]'::jsonb, 53.400000000000006, false, 'active', false),
  ('SIN-TER-27', 'klimatyzator-scienny-sinclair-terrel-2-7-kw', 'Klimatyzator ścienny Sinclair Terrel 2.7 kW', '5900000000053', (select id from public.brands where slug = 'sinclair'), (select id from public.categories where slug = 'klimatyzatory-split'), '<p>Zestaw klimatyzacji ściennej Sinclair Terrel o mocy chłodniczej 2.7 kW (jednostka wewnętrzna + zewnętrzna). Czynnik R32, sprężarka inwerterowa, tryb grzania do -15°C, sterowanie Wi‑Fi w standardzie. Zalecany do pomieszczeń do ok. 27 m².</p><ul><li>Filtr antybakteryjny</li><li>Funkcja I Feel</li><li>Timer 24h</li><li>5 lat gwarancji po rejestracji</li></ul>', '{"typ": "ścienny", "moc_chlodnicza_kw": 2.7, "moc_grzewcza_kw": 3.0, "czynnik": "R32", "klasa_energetyczna_chlodzenie": "A++", "klasa_energetyczna_grzanie": "A+", "seer": 6.5, "scop": 4.1, "poziom_halasu_db": 21, "zasilanie": "1-fazowe", "wifi": true, "powierzchnia_m2": 27}'::jsonb, array['https://placehold.co/800x800/F8FAFC/0F172A?text=SIN-TER-27'], '[{"name": "Karta katalogowa", "url": "https://example.com/docs/SIN-TER-27.pdf", "type": "karta"}]'::jsonb, 43.94, false, 'active', false),
  ('SIN-TER-35', 'klimatyzator-scienny-sinclair-terrel-3-5-kw', 'Klimatyzator ścienny Sinclair Terrel 3.5 kW', '5900000000060', (select id from public.brands where slug = 'sinclair'), (select id from public.categories where slug = 'klimatyzatory-split'), '<p>Zestaw klimatyzacji ściennej Sinclair Terrel o mocy chłodniczej 3.5 kW (jednostka wewnętrzna + zewnętrzna). Czynnik R32, sprężarka inwerterowa, tryb grzania do -15°C, sterowanie Wi‑Fi w standardzie. Zalecany do pomieszczeń do ok. 35 m².</p><ul><li>Filtr antybakteryjny</li><li>Funkcja I Feel</li><li>Timer 24h</li><li>5 lat gwarancji po rejestracji</li></ul>', '{"typ": "ścienny", "moc_chlodnicza_kw": 3.5, "moc_grzewcza_kw": 3.8, "czynnik": "R32", "klasa_energetyczna_chlodzenie": "A++", "klasa_energetyczna_grzanie": "A+", "seer": 6.5, "scop": 4.1, "poziom_halasu_db": 22, "zasilanie": "1-fazowe", "wifi": true, "powierzchnia_m2": 35}'::jsonb, array['https://placehold.co/800x800/F8FAFC/0F172A?text=SIN-TER-35'], '[{"name": "Karta katalogowa", "url": "https://example.com/docs/SIN-TER-35.pdf", "type": "karta"}]'::jsonb, 45.7, false, 'active', true),
  ('SIN-TER-53', 'klimatyzator-scienny-sinclair-terrel-5-3-kw', 'Klimatyzator ścienny Sinclair Terrel 5.3 kW', '5900000000077', (select id from public.brands where slug = 'sinclair'), (select id from public.categories where slug = 'klimatyzatory-split'), '<p>Zestaw klimatyzacji ściennej Sinclair Terrel o mocy chłodniczej 5.3 kW (jednostka wewnętrzna + zewnętrzna). Czynnik R32, sprężarka inwerterowa, tryb grzania do -15°C, sterowanie Wi‑Fi w standardzie. Zalecany do pomieszczeń do ok. 53 m².</p><ul><li>Filtr antybakteryjny</li><li>Funkcja I Feel</li><li>Timer 24h</li><li>5 lat gwarancji po rejestracji</li></ul>', '{"typ": "ścienny", "moc_chlodnicza_kw": 5.3, "moc_grzewcza_kw": 5.5, "czynnik": "R32", "klasa_energetyczna_chlodzenie": "A++", "klasa_energetyczna_grzanie": "A+", "seer": 6.5, "scop": 4.1, "poziom_halasu_db": 23, "zasilanie": "1-fazowe", "wifi": true, "powierzchnia_m2": 53}'::jsonb, array['https://placehold.co/800x800/F8FAFC/0F172A?text=SIN-TER-53'], '[{"name": "Karta katalogowa", "url": "https://example.com/docs/SIN-TER-53.pdf", "type": "karta"}]'::jsonb, 49.66, false, 'active', false),
  ('GRE-AMB-25', 'klimatyzator-scienny-gree-amber-prestige-2-5-kw', 'Klimatyzator ścienny Gree Amber Prestige 2.5 kW', '5900000000091', (select id from public.brands where slug = 'gree'), (select id from public.categories where slug = 'klimatyzatory-split'), '<p>Zestaw klimatyzacji ściennej Gree Amber Prestige o mocy chłodniczej 2.5 kW (jednostka wewnętrzna + zewnętrzna). Czynnik R32, sprężarka inwerterowa, tryb grzania do -15°C, sterowanie Wi‑Fi w standardzie. Zalecany do pomieszczeń do ok. 25 m².</p><ul><li>Filtr antybakteryjny</li><li>Funkcja I Feel</li><li>Timer 24h</li><li>5 lat gwarancji po rejestracji</li></ul>', '{"typ": "ścienny", "moc_chlodnicza_kw": 2.5, "moc_grzewcza_kw": 3.2, "czynnik": "R32", "klasa_energetyczna_chlodzenie": "A+++", "klasa_energetyczna_grzanie": "A++", "seer": 8.5, "scop": 4.6, "poziom_halasu_db": 19, "zasilanie": "1-fazowe", "wifi": true, "powierzchnia_m2": 25}'::jsonb, array['https://placehold.co/800x800/F8FAFC/0F172A?text=GRE-AMB-25'], '[{"name": "Karta katalogowa", "url": "https://example.com/docs/GRE-AMB-25.pdf", "type": "karta"}]'::jsonb, 43.5, false, 'active', false),
  ('GRE-AMB-35', 'klimatyzator-scienny-gree-amber-prestige-3-5-kw', 'Klimatyzator ścienny Gree Amber Prestige 3.5 kW', '5900000000107', (select id from public.brands where slug = 'gree'), (select id from public.categories where slug = 'klimatyzatory-split'), '<p>Zestaw klimatyzacji ściennej Gree Amber Prestige o mocy chłodniczej 3.5 kW (jednostka wewnętrzna + zewnętrzna). Czynnik R32, sprężarka inwerterowa, tryb grzania do -15°C, sterowanie Wi‑Fi w standardzie. Zalecany do pomieszczeń do ok. 35 m².</p><ul><li>Filtr antybakteryjny</li><li>Funkcja I Feel</li><li>Timer 24h</li><li>5 lat gwarancji po rejestracji</li></ul>', '{"typ": "ścienny", "moc_chlodnicza_kw": 3.5, "moc_grzewcza_kw": 3.8, "czynnik": "R32", "klasa_energetyczna_chlodzenie": "A+++", "klasa_energetyczna_grzanie": "A++", "seer": 8.5, "scop": 4.6, "poziom_halasu_db": 20, "zasilanie": "1-fazowe", "wifi": true, "powierzchnia_m2": 35}'::jsonb, array['https://placehold.co/800x800/F8FAFC/0F172A?text=GRE-AMB-35'], '[{"name": "Karta katalogowa", "url": "https://example.com/docs/GRE-AMB-35.pdf", "type": "karta"}]'::jsonb, 45.7, false, 'active', true),
  ('GRE-AMB-53', 'klimatyzator-scienny-gree-amber-prestige-5-3-kw', 'Klimatyzator ścienny Gree Amber Prestige 5.3 kW', '5900000000114', (select id from public.brands where slug = 'gree'), (select id from public.categories where slug = 'klimatyzatory-split'), '<p>Zestaw klimatyzacji ściennej Gree Amber Prestige o mocy chłodniczej 5.3 kW (jednostka wewnętrzna + zewnętrzna). Czynnik R32, sprężarka inwerterowa, tryb grzania do -15°C, sterowanie Wi‑Fi w standardzie. Zalecany do pomieszczeń do ok. 53 m².</p><ul><li>Filtr antybakteryjny</li><li>Funkcja I Feel</li><li>Timer 24h</li><li>5 lat gwarancji po rejestracji</li></ul>', '{"typ": "ścienny", "moc_chlodnicza_kw": 5.3, "moc_grzewcza_kw": 5.5, "czynnik": "R32", "klasa_energetyczna_chlodzenie": "A+++", "klasa_energetyczna_grzanie": "A++", "seer": 8.5, "scop": 4.6, "poziom_halasu_db": 21, "zasilanie": "1-fazowe", "wifi": true, "powierzchnia_m2": 53}'::jsonb, array['https://placehold.co/800x800/F8FAFC/0F172A?text=GRE-AMB-53'], '[{"name": "Karta katalogowa", "url": "https://example.com/docs/GRE-AMB-53.pdf", "type": "karta"}]'::jsonb, 49.66, false, 'active', false),
  ('ROT-RON-26', 'klimatyzator-scienny-rotenso-roni-2-6-kw', 'Klimatyzator ścienny Rotenso Roni 2.6 kW', '5900000000138', (select id from public.brands where slug = 'rotenso'), (select id from public.categories where slug = 'klimatyzatory-split'), '<p>Zestaw klimatyzacji ściennej Rotenso Roni o mocy chłodniczej 2.6 kW (jednostka wewnętrzna + zewnętrzna). Czynnik R32, sprężarka inwerterowa, tryb grzania do -15°C, opcjonalny moduł Wi‑Fi. Zalecany do pomieszczeń do ok. 26 m².</p><ul><li>Filtr antybakteryjny</li><li>Funkcja I Feel</li><li>Timer 24h</li><li>5 lat gwarancji po rejestracji</li></ul>', '{"typ": "ścienny", "moc_chlodnicza_kw": 2.6, "moc_grzewcza_kw": 2.9, "czynnik": "R32", "klasa_energetyczna_chlodzenie": "A++", "klasa_energetyczna_grzanie": "A+", "seer": 6.1, "scop": 4.0, "poziom_halasu_db": 23, "zasilanie": "1-fazowe", "wifi": false, "powierzchnia_m2": 26}'::jsonb, array['https://placehold.co/800x800/F8FAFC/0F172A?text=ROT-RON-26'], '[{"name": "Karta katalogowa", "url": "https://example.com/docs/ROT-RON-26.pdf", "type": "karta"}]'::jsonb, 43.72, false, 'active', false),
  ('ROT-RON-35', 'klimatyzator-scienny-rotenso-roni-3-5-kw', 'Klimatyzator ścienny Rotenso Roni 3.5 kW', '5900000000145', (select id from public.brands where slug = 'rotenso'), (select id from public.categories where slug = 'klimatyzatory-split'), '<p>Zestaw klimatyzacji ściennej Rotenso Roni o mocy chłodniczej 3.5 kW (jednostka wewnętrzna + zewnętrzna). Czynnik R32, sprężarka inwerterowa, tryb grzania do -15°C, opcjonalny moduł Wi‑Fi. Zalecany do pomieszczeń do ok. 35 m².</p><ul><li>Filtr antybakteryjny</li><li>Funkcja I Feel</li><li>Timer 24h</li><li>5 lat gwarancji po rejestracji</li></ul>', '{"typ": "ścienny", "moc_chlodnicza_kw": 3.5, "moc_grzewcza_kw": 3.6, "czynnik": "R32", "klasa_energetyczna_chlodzenie": "A++", "klasa_energetyczna_grzanie": "A+", "seer": 6.1, "scop": 4.0, "poziom_halasu_db": 24, "zasilanie": "1-fazowe", "wifi": false, "powierzchnia_m2": 35}'::jsonb, array['https://placehold.co/800x800/F8FAFC/0F172A?text=ROT-RON-35'], '[{"name": "Karta katalogowa", "url": "https://example.com/docs/ROT-RON-35.pdf", "type": "karta"}]'::jsonb, 45.7, false, 'active', false),
  ('MID-XTR-26', 'klimatyzator-scienny-midea-xtreme-save-2-6-kw', 'Klimatyzator ścienny Midea Xtreme Save 2.6 kW', '5900000000176', (select id from public.brands where slug = 'midea'), (select id from public.categories where slug = 'klimatyzatory-split'), '<p>Zestaw klimatyzacji ściennej Midea Xtreme Save o mocy chłodniczej 2.6 kW (jednostka wewnętrzna + zewnętrzna). Czynnik R32, sprężarka inwerterowa, tryb grzania do -15°C, sterowanie Wi‑Fi w standardzie. Zalecany do pomieszczeń do ok. 26 m².</p><ul><li>Filtr antybakteryjny</li><li>Funkcja I Feel</li><li>Timer 24h</li><li>5 lat gwarancji po rejestracji</li></ul>', '{"typ": "ścienny", "moc_chlodnicza_kw": 2.6, "moc_grzewcza_kw": 2.9, "czynnik": "R32", "klasa_energetyczna_chlodzenie": "A+++", "klasa_energetyczna_grzanie": "A+", "seer": 7.0, "scop": 4.2, "poziom_halasu_db": 21, "zasilanie": "1-fazowe", "wifi": true, "powierzchnia_m2": 26}'::jsonb, array['https://placehold.co/800x800/F8FAFC/0F172A?text=MID-XTR-26'], '[{"name": "Karta katalogowa", "url": "https://example.com/docs/MID-XTR-26.pdf", "type": "karta"}]'::jsonb, 43.72, false, 'active', false),
  ('KAI-MULTI-2X', 'jednostka-zewnetrzna-multi-split-kaisai-2x-5-3-kw', 'Jednostka zewnętrzna multi-split KAISAI 2x (5.3 kW)', '5900000000206', (select id from public.brands where slug = 'kaisai'), (select id from public.categories where slug = 'multi-split'), '<p>Jednostka zewnętrzna systemu multi-split KAISAI do podłączenia 2 jednostek wewnętrznych (ścienne, kasetonowe lub kanałowe).</p>', '{"typ": "multi-split", "moc_chlodnicza_kw": 5.3, "moc_grzewcza_kw": 5.6, "czynnik": "R32", "liczba_jednostek": 2, "zasilanie": "1-fazowe", "klasa_energetyczna_chlodzenie": "A++", "klasa_energetyczna_grzanie": "A+", "seer": 6.6, "scop": 4.0}'::jsonb, array['https://placehold.co/800x800/F8FAFC/0F172A?text=KAI-MULTI-2X'], '[{"name": "Karta katalogowa", "url": "https://example.com/docs/KAI-MULTI-2X.pdf", "type": "karta"}]'::jsonb, 44, false, 'active', true),
  ('KAI-MULTI-3X', 'jednostka-zewnetrzna-multi-split-kaisai-3x-7-9-kw', 'Jednostka zewnętrzna multi-split KAISAI 3x (7.9 kW)', '5900000000213', (select id from public.brands where slug = 'kaisai'), (select id from public.categories where slug = 'multi-split'), '<p>Jednostka zewnętrzna multi-split KAISAI do 3 jednostek wewnętrznych.</p>', '{"typ": "multi-split", "moc_chlodnicza_kw": 7.9, "moc_grzewcza_kw": 8.2, "czynnik": "R32", "liczba_jednostek": 3, "zasilanie": "1-fazowe", "klasa_energetyczna_chlodzenie": "A++", "klasa_energetyczna_grzanie": "A+", "seer": 6.8, "scop": 4.1}'::jsonb, array['https://placehold.co/800x800/F8FAFC/0F172A?text=KAI-MULTI-3X'], '[{"name": "Karta katalogowa", "url": "https://example.com/docs/KAI-MULTI-3X.pdf", "type": "karta"}]'::jsonb, 58, false, 'active', false),
  ('KAI-IN-WALL-26', 'jednostka-wewnetrzna-scienna-kaisai-eco-multi-2-6-kw', 'Jednostka wewnętrzna ścienna KAISAI Eco multi 2.6 kW', '5900000000237', (select id from public.brands where slug = 'kaisai'), (select id from public.categories where slug = 'multi-split'), '<p>Jednostka wewnętrzna ścienna do systemów multi-split KAISAI.</p>', '{"typ": "jednostka wewnętrzna ścienna", "moc_chlodnicza_kw": 2.6, "moc_grzewcza_kw": 2.9, "czynnik": "R32", "poziom_halasu_db": 22}'::jsonb, array['https://placehold.co/800x800/F8FAFC/0F172A?text=KAI-IN-WALL-26'], '[{"name": "Karta katalogowa", "url": "https://example.com/docs/KAI-IN-WALL-26.pdf", "type": "karta"}]'::jsonb, 9, false, 'active', false),
  ('KAI-CAS-50', 'klimatyzator-kasetonowy-kaisai-5-0-kw-zestaw', 'Klimatyzator kasetonowy KAISAI 5.0 kW (zestaw)', '5900000000251', (select id from public.brands where slug = 'kaisai'), (select id from public.categories where slug = 'kasetonowe'), '<p>Zestaw klimatyzacji kasetonowej 4-stronnej KAISAI do montażu w suficie podwieszanym. W zestawie maskownica.</p>', '{"typ": "kasetonowy", "moc_chlodnicza_kw": 5.0, "moc_grzewcza_kw": 5.6, "czynnik": "R32", "zasilanie": "1-fazowe", "klasa_energetyczna_chlodzenie": "A++", "klasa_energetyczna_grzanie": "A+", "seer": 6.1, "scop": 4.0}'::jsonb, array['https://placehold.co/800x800/F8FAFC/0F172A?text=KAI-CAS-50'], '[{"name": "Karta katalogowa", "url": "https://example.com/docs/KAI-CAS-50.pdf", "type": "karta"}]'::jsonb, 62, true, 'active', false),
  ('SIN-DUCT-53', 'klimatyzator-kanaowy-sinclair-5-3-kw-zestaw', 'Klimatyzator kanałowy Sinclair 5.3 kW (zestaw)', '5900000000282', (select id from public.brands where slug = 'sinclair'), (select id from public.categories where slug = 'kanalowe'), '<p>Zestaw klimatyzacji kanałowej Sinclair o niskim sprężu, do zabudowy w suficie.</p>', '{"typ": "kanałowy", "moc_chlodnicza_kw": 5.3, "moc_grzewcza_kw": 5.8, "czynnik": "R32", "zasilanie": "1-fazowe", "klasa_energetyczna_chlodzenie": "A+", "klasa_energetyczna_grzanie": "A+", "seer": 6.0, "scop": 3.9, "spręż_pa": 80}'::jsonb, array['https://placehold.co/800x800/F8FAFC/0F172A?text=SIN-DUCT-53'], '[{"name": "Karta katalogowa", "url": "https://example.com/docs/SIN-DUCT-53.pdf", "type": "karta"}]'::jsonb, 58, true, 'active', false),
  ('MID-PORT-26', 'klimatyzator-przenosny-midea-comfee-2-6-kw', 'Klimatyzator przenośny Midea Comfee 2.6 kW', '5900000000305', (select id from public.brands where slug = 'midea'), (select id from public.categories where slug = 'przenosne'), '<p>Klimatyzator przenośny z funkcją osuszania i wentylacji, aplikacja mobilna, zestaw okienny w komplecie.</p>', '{"typ": "przenośny", "moc_chlodnicza_kw": 2.6, "czynnik": "R290", "zasilanie": "1-fazowe", "klasa_energetyczna_chlodzenie": "A", "poziom_halasu_db": 52, "wifi": true}'::jsonb, array['https://placehold.co/800x800/F8FAFC/0F172A?text=MID-PORT-26'], '[{"name": "Karta katalogowa", "url": "https://example.com/docs/MID-PORT-26.pdf", "type": "karta"}]'::jsonb, 24, false, 'active', true),
  ('KAI-HP-MONO-08', 'pompa-ciepa-kaisai-arctic-monoblok-8-kw-1f', 'Pompa ciepła KAISAI Arctic monoblok 8 kW 1F', '5900000000329', (select id from public.brands where slug = 'kaisai'), (select id from public.categories where slug = 'monoblok'), '<p>Pompa ciepła powietrze-woda typu monoblok z czynnikiem R32, praca do -25°C, zasilanie 1-fazowe. Wbudowany moduł hydrauliczny.</p>', '{"typ": "monoblok", "moc_grzewcza_kw": 8.0, "czynnik": "R32", "zasilanie": "1-fazowe", "klasa_energetyczna_grzanie": "A+++", "scop": 4.7, "temp_zasilania_max_c": 65, "poziom_halasu_db": 49}'::jsonb, array['https://placehold.co/800x800/F8FAFC/0F172A?text=KAI-HP-MONO-08'], '[{"name": "Karta katalogowa", "url": "https://example.com/docs/KAI-HP-MONO-08.pdf", "type": "karta"}]'::jsonb, 110, true, 'active', true),
  ('KAI-HP-MONO-12', 'pompa-ciepa-kaisai-arctic-monoblok-12-kw-3f', 'Pompa ciepła KAISAI Arctic monoblok 12 kW 3F', '5900000000336', (select id from public.brands where slug = 'kaisai'), (select id from public.categories where slug = 'monoblok'), '<p>Pompa ciepła powietrze-woda monoblok 12 kW, zasilanie 3-fazowe.</p>', '{"typ": "monoblok", "moc_grzewcza_kw": 12.0, "czynnik": "R32", "zasilanie": "3-fazowe", "klasa_energetyczna_grzanie": "A+++", "scop": 4.6, "temp_zasilania_max_c": 65, "poziom_halasu_db": 52}'::jsonb, array['https://placehold.co/800x800/F8FAFC/0F172A?text=KAI-HP-MONO-12'], '[{"name": "Karta katalogowa", "url": "https://example.com/docs/KAI-HP-MONO-12.pdf", "type": "karta"}]'::jsonb, 135, true, 'active', false),
  ('SIN-HP-SPLIT-10', 'pompa-ciepa-sinclair-split-10-kw-1f-zestaw', 'Pompa ciepła Sinclair split 10 kW 1F (zestaw)', '5900000000350', (select id from public.brands where slug = 'sinclair'), (select id from public.categories where slug = 'pompy-split'), '<p>Pompa ciepła typu split z jednostką wewnętrzną hydrobox, 10 kW.</p>', '{"typ": "split", "moc_grzewcza_kw": 10.0, "czynnik": "R32", "zasilanie": "1-fazowe", "klasa_energetyczna_grzanie": "A+++", "scop": 4.8, "temp_zasilania_max_c": 60}'::jsonb, array['https://placehold.co/800x800/F8FAFC/0F172A?text=SIN-HP-SPLIT-10'], '[{"name": "Karta katalogowa", "url": "https://example.com/docs/SIN-HP-SPLIT-10.pdf", "type": "karta"}]'::jsonb, 150, true, 'active', false),
  ('MID-CWU-200', 'pompa-ciepa-do-cwu-midea-200-l', 'Pompa ciepła do CWU Midea 200 l', '5900000000374', (select id from public.brands where slug = 'midea'), (select id from public.categories where slug = 'cwu'), '<p>Pompa ciepła do ciepłej wody użytkowej ze zbiornikiem 200 l i wężownicą solarną.</p>', '{"typ": "CWU", "pojemnosc_l": 200, "moc_grzewcza_kw": 2.2, "czynnik": "R134a", "zasilanie": "1-fazowe", "klasa_energetyczna_grzanie": "A+", "temp_zasilania_max_c": 60}'::jsonb, array['https://placehold.co/800x800/F8FAFC/0F172A?text=MID-CWU-200'], '[{"name": "Karta katalogowa", "url": "https://example.com/docs/MID-CWU-200.pdf", "type": "karta"}]'::jsonb, 95, true, 'active', false),
  ('ROT-VEN-350', 'rekuperator-rotenso-ventilo-350-m3-h', 'Rekuperator Rotenso Ventilo 350 m³/h', '5900000000398', (select id from public.brands where slug = 'rotenso'), (select id from public.categories where slug = 'rekuperatory'), '<p>Centrala rekuperacyjna z wymiennikiem przeciwprądowym, bypass automatyczny, sterowanie przez aplikację.</p>', '{"typ": "rekuperator", "wydajnosc_m3h": 350, "odzysk_ciepla_pct": 92, "zasilanie": "1-fazowe", "klasa_energetyczna_chlodzenie": "A", "poziom_halasu_db": 38, "wifi": true}'::jsonb, array['https://placehold.co/800x800/F8FAFC/0F172A?text=ROT-VEN-350'], '[{"name": "Karta katalogowa", "url": "https://example.com/docs/ROT-VEN-350.pdf", "type": "karta"}]'::jsonb, 48, true, 'active', true),
  ('KAI-VEN-300', 'rekuperator-kaisai-airvent-300-m3-h', 'Rekuperator KAISAI AirVent 300 m³/h', '5900000000411', (select id from public.brands where slug = 'kaisai'), (select id from public.categories where slug = 'rekuperatory'), '<p>Rekuperator KAISAI 300 m³/h z wymiennikiem entalpicznym.</p>', '{"typ": "rekuperator", "wydajnosc_m3h": 300, "odzysk_ciepla_pct": 90, "zasilanie": "1-fazowe", "klasa_energetyczna_chlodzenie": "A", "poziom_halasu_db": 37, "wifi": true}'::jsonb, array['https://placehold.co/800x800/F8FAFC/0F172A?text=KAI-VEN-300'], '[{"name": "Karta katalogowa", "url": "https://example.com/docs/KAI-VEN-300.pdf", "type": "karta"}]'::jsonb, 45, true, 'active', false),
  ('VEN-FAN-100', 'wentylator-kanaowy-vents-tt-100', 'Wentylator kanałowy Vents TT 100', '5900000000428', (select id from public.brands where slug = 'vents'), (select id from public.categories where slug = 'wentylatory'), '<p>Dwubiegowy wentylator kanałowy do przewodów Ø100 mm.</p>', '{"typ": "wentylator kanałowy", "srednica_mm": 100, "wydajnosc_m3h": 187, "zasilanie": "1-fazowe", "poziom_halasu_db": 33}'::jsonb, array['https://placehold.co/800x800/F8FAFC/0F172A?text=VEN-FAN-100'], '[{"name": "Karta katalogowa", "url": "https://example.com/docs/VEN-FAN-100.pdf", "type": "karta"}]'::jsonb, 1.4, false, 'active', false),
  ('VEN-DUCT-125-3', 'kana-spiro-ocynk-125-mm-3-m', 'Kanał spiro ocynk Ø125 mm, 3 m', '5900000000442', (select id from public.brands where slug = 'vents'), (select id from public.categories where slug = 'kanaly-i-ksztaltki'), '<p>Przewód wentylacyjny spiro z blachy ocynkowanej Ø125, odcinek 3 m.</p>', '{"srednica_mm": 125, "dlugosc_m": 3}'::jsonb, array['https://placehold.co/800x800/F8FAFC/0F172A?text=VEN-DUCT-125-3'], '[{"name": "Karta katalogowa", "url": "https://example.com/docs/VEN-DUCT-125-3.pdf", "type": "karta"}]'::jsonb, 2.4, false, 'active', false),
  ('HON-R32-9', 'czynnik-chodniczy-r32-butla-9-kg', 'Czynnik chłodniczy R32, butla 9 kg', '5900000000466', (select id from public.brands where slug = 'honeywell'), (select id from public.categories where slug = 'czynniki-chlodnicze'), '<p>Czynnik R32 w butli zwrotnej 9 kg. Sprzedaż wyłącznie dla firm z certyfikatem F-gazowym (NIP wymagany).</p>', '{"czynnik": "R32", "pojemnosc_kg": 9, "typ": "butla zwrotna"}'::jsonb, array['https://placehold.co/800x800/F8FAFC/0F172A?text=HON-R32-9'], '[{"name": "Karta katalogowa", "url": "https://example.com/docs/HON-R32-9.pdf", "type": "karta"}]'::jsonb, 14, false, 'active', false),
  ('REF-VAC-42', 'pompa-prozniowa-refco-rl-4-2-stopniowa-42-l-min', 'Pompa próżniowa Refco RL-4 2-stopniowa 42 l/min', '5900000000480', (select id from public.brands where slug = 'refco'), (select id from public.categories where slug = 'narzedzia'), '<p>Dwustopniowa pompa próżniowa 42 l/min z zaworem elektromagnetycznym, do R32/R410A.</p>', '{"typ": "pompa próżniowa", "wydajnosc_lmin": 42, "zasilanie": "1-fazowe"}'::jsonb, array['https://placehold.co/800x800/F8FAFC/0F172A?text=REF-VAC-42'], '[{"name": "Karta katalogowa", "url": "https://example.com/docs/REF-VAC-42.pdf", "type": "karta"}]'::jsonb, 7.5, false, 'active', true),
  ('REF-MAN-R32', 'zestaw-manometrow-refco-r32-r410a-z-wezami', 'Zestaw manometrów Refco R32/R410A z wężami', '5900000000497', (select id from public.brands where slug = 'refco'), (select id from public.categories where slug = 'manometry-i-pompy-prozniowe'), '<p>Zestaw manometrów dwuzaworowych z wężami 150 cm do R32 i R410A.</p>', '{"typ": "manometry", "czynnik": "R32/R410A"}'::jsonb, array['https://placehold.co/800x800/F8FAFC/0F172A?text=REF-MAN-R32'], '[{"name": "Karta katalogowa", "url": "https://example.com/docs/REF-MAN-R32.pdf", "type": "karta"}]'::jsonb, 1.8, false, 'active', false),
  ('CU-14', 'rura-miedziana-1-4-w-otulinie-krag-15-m', 'Rura miedziana 1/4" w otulinie, krąg 15 m', '5900000000527', (select id from public.brands where slug = 'armacell'), (select id from public.categories where slug = 'rury-miedziane'), '<p>Rura miedziana chłodnicza 1/4" w otulinie 9 mm, krąg 15 m. Do instalacji R32/R410A.</p>', '{"srednica_cal": "1/4\"", "dlugosc_m": 15, "izolacja": "9 mm"}'::jsonb, array['https://placehold.co/800x800/F8FAFC/0F172A?text=CU-14'], '[{"name": "Karta katalogowa", "url": "https://example.com/docs/CU-14.pdf", "type": "karta"}]'::jsonb, 5.0, false, 'active', false),
  ('CU-38', 'rura-miedziana-3-8-w-otulinie-krag-15-m', 'Rura miedziana 3/8" w otulinie, krąg 15 m', '5900000000534', (select id from public.brands where slug = 'armacell'), (select id from public.categories where slug = 'rury-miedziane'), '<p>Rura miedziana chłodnicza 3/8" w otulinie 9 mm, krąg 15 m. Do instalacji R32/R410A.</p>', '{"srednica_cal": "3/8\"", "dlugosc_m": 15, "izolacja": "9 mm"}'::jsonb, array['https://placehold.co/800x800/F8FAFC/0F172A?text=CU-38'], '[{"name": "Karta katalogowa", "url": "https://example.com/docs/CU-38.pdf", "type": "karta"}]'::jsonb, 7.8, false, 'active', false),
  ('WSP-450', 'wspornik-jednostki-zewnetrznej-450-mm-do-100-kg', 'Wspornik jednostki zewnętrznej 450 mm, do 100 kg', '5900000000572', (select id from public.brands where slug = 'rawicom'), (select id from public.categories where slug = 'wsporniki'), '<p>Wspornik ścienny ocynkowany, lakierowany proszkowo, komplet ze śrubami.</p>', '{"dlugosc_mm": 450, "udzwig_kg": 100}'::jsonb, array['https://placehold.co/800x800/F8FAFC/0F172A?text=WSP-450'], '[{"name": "Karta katalogowa", "url": "https://example.com/docs/WSP-450.pdf", "type": "karta"}]'::jsonb, 2.6, false, 'active', false),
  ('ASP-MINI-LIME', 'pompka-skroplin-aspen-mini-lime', 'Pompka skroplin Aspen Mini Lime', '5900000000602', (select id from public.brands where slug = 'aspen'), (select id from public.categories where slug = 'pompki-skroplin'), '<p>Cicha pompka skroplin do klimatyzatorów ściennych do 10 kW.</p>', '{"typ": "pompka skroplin", "wydajnosc_lh": 12, "podnoszenie_m": 10, "poziom_halasu_db": 21}'::jsonb, array['https://placehold.co/800x800/F8FAFC/0F172A?text=ASP-MINI-LIME'], '[{"name": "Karta katalogowa", "url": "https://example.com/docs/ASP-MINI-LIME.pdf", "type": "karta"}]'::jsonb, 0.5, false, 'active', true),
  ('KAB-OMY-5x15', 'przewod-omy-5x1-5-mm2-50-m', 'Przewód OMY 5x1,5 mm², 50 m', '5900000000626', (select id from public.brands where slug = 'elektrokabel'), (select id from public.categories where slug = 'kable-i-przewody'), '<p>Przewód sterujący do połączenia jednostek klimatyzatora, krąg 50 m.</p>', '{"przekroj_mm2": 1.5, "liczba_zyl": 5, "dlugosc_m": 50}'::jsonb, array['https://placehold.co/800x800/F8FAFC/0F172A?text=KAB-OMY-5x15'], '[{"name": "Karta katalogowa", "url": "https://example.com/docs/KAB-OMY-5x15.pdf", "type": "karta"}]'::jsonb, 6.0, false, 'active', false),
  ('IZO-AF-9-14', 'otulina-armaflex-af-9-mm-na-rure-1-4-2-m', 'Otulina Armaflex AF 9 mm na rurę 1/4", 2 m', '5900000000640', (select id from public.brands where slug = 'armacell'), (select id from public.categories where slug = 'izolacje'), '<p>Otulina kauczukowa Armaflex AF 9 mm, odcinek 2 m.</p>', '{"srednica_cal": "1/4\"", "grubosc_mm": 9, "dlugosc_m": 2}'::jsonb, array['https://placehold.co/800x800/F8FAFC/0F172A?text=IZO-AF-9-14'], '[{"name": "Karta katalogowa", "url": "https://example.com/docs/IZO-AF-9-14.pdf", "type": "karta"}]'::jsonb, 0.2, false, 'active', false),
  ('FIL-KAI-KEX', 'filtr-powietrza-do-kaisai-eco-kex-komplet', 'Filtr powietrza do KAISAI Eco KEX (komplet)', '5900000000671', (select id from public.brands where slug = 'kaisai'), (select id from public.categories where slug = 'filtry'), '<p>Komplet filtrów do jednostek wewnętrznych serii Eco KEX.</p>', '{"typ": "filtr", "pasuje_do": "KAISAI Eco KEX"}'::jsonb, array['https://placehold.co/800x800/F8FAFC/0F172A?text=FIL-KAI-KEX'], '[{"name": "Karta katalogowa", "url": "https://example.com/docs/FIL-KAI-KEX.pdf", "type": "karta"}]'::jsonb, 0.1, false, 'active', false),
  ('PIL-KAI-UNI', 'pilot-do-klimatyzatora-kaisai-oryginalny', 'Pilot do klimatyzatora KAISAI (oryginalny)', '5900000000688', (select id from public.brands where slug = 'kaisai'), (select id from public.categories where slug = 'piloty'), '<p>Oryginalny pilot bezprzewodowy KAISAI.</p>', '{"typ": "pilot", "pasuje_do": "KAISAI"}'::jsonb, array['https://placehold.co/800x800/F8FAFC/0F172A?text=PIL-KAI-UNI'], '[{"name": "Karta katalogowa", "url": "https://example.com/docs/PIL-KAI-UNI.pdf", "type": "karta"}]'::jsonb, 0.1, false, 'active', false),
  ('CZU-TEMP-10K', 'czujnik-temperatury-ntc-10k-uniwersalny', 'Czujnik temperatury NTC 10K uniwersalny', '5900000000718', (select id from public.brands where slug = 'rawicom'), (select id from public.categories where slug = 'plytki-i-czujniki'), '<p>Czujnik NTC 10 kΩ z przewodem 1 m, do wymiany w jednostkach wewnętrznych.</p>', '{"typ": "czujnik", "pasuje_do": "uniwersalny"}'::jsonb, array['https://placehold.co/800x800/F8FAFC/0F172A?text=CZU-TEMP-10K'], '[{"name": "Karta katalogowa", "url": "https://example.com/docs/CZU-TEMP-10K.pdf", "type": "karta"}]'::jsonb, 0.05, false, 'active', false)
on conflict (sku) do nothing;

-- --- Oferty hurtowni mock dla produktów demo (żeby ceny istniały bez uruchamiania syncu) ---
insert into public.supplier_offers (supplier_id, product_id, supplier_sku, ean, name_raw, brand_raw, purchase_net_cents, stock, lead_time_days, raw) values
  ((select id from public.suppliers where code = 'mock'), (select id from public.products where sku = 'KAI-KEX-26'), 'MOCK-KAI-KEX-26', '5900000000015', 'Klimatyzator ścienny KAISAI Eco KEX 2.6 kW', 'KAISAI', 199000, 5, null, '{}'::jsonb),
  ((select id from public.suppliers where code = 'mock'), (select id from public.products where sku = 'KAI-KEX-35'), 'MOCK-KAI-KEX-35', '5900000000022', 'Klimatyzator ścienny KAISAI Eco KEX 3.5 kW', 'KAISAI', 234800, 19, null, '{}'::jsonb),
  ((select id from public.suppliers where code = 'mock'), (select id from public.products where sku = 'KAI-KEX-53'), 'MOCK-KAI-KEX-53', '5900000000039', 'Klimatyzator ścienny KAISAI Eco KEX 5.3 kW', 'KAISAI', 322400, 3, null, '{}'::jsonb),
  ((select id from public.suppliers where code = 'mock'), (select id from public.products where sku = 'KAI-KEX-70'), 'MOCK-KAI-KEX-70', '5900000000046', 'Klimatyzator ścienny KAISAI Eco KEX 7.0 kW', 'KAISAI', 417900, 0, 14, '{}'::jsonb),
  ((select id from public.suppliers where code = 'mock'), (select id from public.products where sku = 'SIN-TER-27'), 'MOCK-SIN-TER-27', '5900000000053', 'Klimatyzator ścienny Sinclair Terrel 2.7 kW', 'Sinclair', 215000, 9, null, '{}'::jsonb),
  ((select id from public.suppliers where code = 'mock'), (select id from public.products where sku = 'SIN-TER-35'), 'MOCK-SIN-TER-35', '5900000000060', 'Klimatyzator ścienny Sinclair Terrel 3.5 kW', 'Sinclair', 258000, 6, null, '{}'::jsonb),
  ((select id from public.suppliers where code = 'mock'), (select id from public.products where sku = 'SIN-TER-53'), 'MOCK-SIN-TER-53', '5900000000077', 'Klimatyzator ścienny Sinclair Terrel 5.3 kW', 'Sinclair', 354800, 0, 7, '{}'::jsonb),
  ((select id from public.suppliers where code = 'mock'), (select id from public.products where sku = 'GRE-AMB-25'), 'MOCK-GRE-AMB-25', '5900000000091', 'Klimatyzator ścienny Gree Amber Prestige 2.5 kW', 'Gree', 265000, 0, 7, '{}'::jsonb),
  ((select id from public.suppliers where code = 'mock'), (select id from public.products where sku = 'GRE-AMB-35'), 'MOCK-GRE-AMB-35', '5900000000107', 'Klimatyzator ścienny Gree Amber Prestige 3.5 kW', 'Gree', 318000, 48, null, '{}'::jsonb),
  ((select id from public.suppliers where code = 'mock'), (select id from public.products where sku = 'GRE-AMB-53'), 'MOCK-GRE-AMB-53', '5900000000114', 'Klimatyzator ścienny Gree Amber Prestige 5.3 kW', 'Gree', 424000, 18, null, '{}'::jsonb),
  ((select id from public.suppliers where code = 'mock'), (select id from public.products where sku = 'ROT-RON-26'), 'MOCK-ROT-RON-26', '5900000000138', 'Klimatyzator ścienny Rotenso Roni 2.6 kW', 'Rotenso', 185000, 4, null, '{}'::jsonb),
  ((select id from public.suppliers where code = 'mock'), (select id from public.products where sku = 'ROT-RON-35'), 'MOCK-ROT-RON-35', '5900000000145', 'Klimatyzator ścienny Rotenso Roni 3.5 kW', 'Rotenso', 212800, 14, null, '{}'::jsonb),
  ((select id from public.suppliers where code = 'mock'), (select id from public.products where sku = 'MID-XTR-26'), 'MOCK-MID-XTR-26', '5900000000176', 'Klimatyzator ścienny Midea Xtreme Save 2.6 kW', 'Midea', 189000, 25, null, '{}'::jsonb),
  ((select id from public.suppliers where code = 'mock'), (select id from public.products where sku = 'KAI-MULTI-2X'), 'MOCK-KAI-MULTI-2X', '5900000000206', 'Jednostka zewnętrzna multi-split KAISAI 2x (5.3 kW)', 'KAISAI', 329000, 55, null, '{}'::jsonb),
  ((select id from public.suppliers where code = 'mock'), (select id from public.products where sku = 'KAI-MULTI-3X'), 'MOCK-KAI-MULTI-3X', '5900000000213', 'Jednostka zewnętrzna multi-split KAISAI 3x (7.9 kW)', 'KAISAI', 459000, 0, 10, '{}'::jsonb),
  ((select id from public.suppliers where code = 'mock'), (select id from public.products where sku = 'KAI-IN-WALL-26'), 'MOCK-KAI-IN-WALL-26', '5900000000237', 'Jednostka wewnętrzna ścienna KAISAI Eco multi 2.6 kW', 'KAISAI', 79000, 0, 10, '{}'::jsonb),
  ((select id from public.suppliers where code = 'mock'), (select id from public.products where sku = 'KAI-CAS-50'), 'MOCK-KAI-CAS-50', '5900000000251', 'Klimatyzator kasetonowy KAISAI 5.0 kW (zestaw)', 'KAISAI', 489000, 27, null, '{}'::jsonb),
  ((select id from public.suppliers where code = 'mock'), (select id from public.products where sku = 'SIN-DUCT-53'), 'MOCK-SIN-DUCT-53', '5900000000282', 'Klimatyzator kanałowy Sinclair 5.3 kW (zestaw)', 'Sinclair', 469000, 2, null, '{}'::jsonb),
  ((select id from public.suppliers where code = 'mock'), (select id from public.products where sku = 'MID-PORT-26'), 'MOCK-MID-PORT-26', '5900000000305', 'Klimatyzator przenośny Midea Comfee 2.6 kW', 'Midea', 109000, 1, null, '{}'::jsonb),
  ((select id from public.suppliers where code = 'mock'), (select id from public.products where sku = 'KAI-HP-MONO-08'), 'MOCK-KAI-HP-MONO-08', '5900000000329', 'Pompa ciepła KAISAI Arctic monoblok 8 kW 1F', 'KAISAI', 1490000, 27, null, '{}'::jsonb),
  ((select id from public.suppliers where code = 'mock'), (select id from public.products where sku = 'KAI-HP-MONO-12'), 'MOCK-KAI-HP-MONO-12', '5900000000336', 'Pompa ciepła KAISAI Arctic monoblok 12 kW 3F', 'KAISAI', 1890000, 2, null, '{}'::jsonb),
  ((select id from public.suppliers where code = 'mock'), (select id from public.products where sku = 'SIN-HP-SPLIT-10'), 'MOCK-SIN-HP-SPLIT-10', '5900000000350', 'Pompa ciepła Sinclair split 10 kW 1F (zestaw)', 'Sinclair', 1690000, 47, null, '{}'::jsonb),
  ((select id from public.suppliers where code = 'mock'), (select id from public.products where sku = 'MID-CWU-200'), 'MOCK-MID-CWU-200', '5900000000374', 'Pompa ciepła do CWU Midea 200 l', 'Midea', 549000, 14, null, '{}'::jsonb),
  ((select id from public.suppliers where code = 'mock'), (select id from public.products where sku = 'ROT-VEN-350'), 'MOCK-ROT-VEN-350', '5900000000398', 'Rekuperator Rotenso Ventilo 350 m³/h', 'Rotenso', 529000, 2, null, '{}'::jsonb),
  ((select id from public.suppliers where code = 'mock'), (select id from public.products where sku = 'KAI-VEN-300'), 'MOCK-KAI-VEN-300', '5900000000411', 'Rekuperator KAISAI AirVent 300 m³/h', 'KAISAI', 479000, 18, null, '{}'::jsonb),
  ((select id from public.suppliers where code = 'mock'), (select id from public.products where sku = 'VEN-FAN-100'), 'MOCK-VEN-FAN-100', '5900000000428', 'Wentylator kanałowy Vents TT 100', 'Vents', 14900, 57, null, '{}'::jsonb),
  ((select id from public.suppliers where code = 'mock'), (select id from public.products where sku = 'VEN-DUCT-125-3'), 'MOCK-VEN-DUCT-125-3', '5900000000442', 'Kanał spiro ocynk Ø125 mm, 3 m', 'Vents', 4200, 1, null, '{}'::jsonb),
  ((select id from public.suppliers where code = 'mock'), (select id from public.products where sku = 'HON-R32-9'), 'MOCK-HON-R32-9', '5900000000466', 'Czynnik chłodniczy R32, butla 9 kg', 'Honeywell', 69000, 17, null, '{}'::jsonb),
  ((select id from public.suppliers where code = 'mock'), (select id from public.products where sku = 'REF-VAC-42'), 'MOCK-REF-VAC-42', '5900000000480', 'Pompa próżniowa Refco RL-4 2-stopniowa 42 l/min', 'Refco', 89000, 24, null, '{}'::jsonb),
  ((select id from public.suppliers where code = 'mock'), (select id from public.products where sku = 'REF-MAN-R32'), 'MOCK-REF-MAN-R32', '5900000000497', 'Zestaw manometrów Refco R32/R410A z wężami', 'Refco', 39000, 2, null, '{}'::jsonb),
  ((select id from public.suppliers where code = 'mock'), (select id from public.products where sku = 'CU-14'), 'MOCK-CU-14', '5900000000527', 'Rura miedziana 1/4" w otulinie, krąg 15 m', 'Armacell', 32000, 3, null, '{}'::jsonb),
  ((select id from public.suppliers where code = 'mock'), (select id from public.products where sku = 'CU-38'), 'MOCK-CU-38', '5900000000534', 'Rura miedziana 3/8" w otulinie, krąg 15 m', 'Armacell', 52000, 20, null, '{}'::jsonb),
  ((select id from public.suppliers where code = 'mock'), (select id from public.products where sku = 'WSP-450'), 'MOCK-WSP-450', '5900000000572', 'Wspornik jednostki zewnętrznej 450 mm, do 100 kg', 'Rawicom', 4900, 9, null, '{}'::jsonb),
  ((select id from public.suppliers where code = 'mock'), (select id from public.products where sku = 'ASP-MINI-LIME'), 'MOCK-ASP-MINI-LIME', '5900000000602', 'Pompka skroplin Aspen Mini Lime', 'Aspen', 24000, 3, null, '{}'::jsonb),
  ((select id from public.suppliers where code = 'mock'), (select id from public.products where sku = 'KAB-OMY-5x15'), 'MOCK-KAB-OMY-5x15', '5900000000626', 'Przewód OMY 5x1,5 mm², 50 m', 'Elektrokabel', 21000, 42, null, '{}'::jsonb),
  ((select id from public.suppliers where code = 'mock'), (select id from public.products where sku = 'IZO-AF-9-14'), 'MOCK-IZO-AF-9-14', '5900000000640', 'Otulina Armaflex AF 9 mm na rurę 1/4", 2 m', 'Armacell', 1800, 39, null, '{}'::jsonb),
  ((select id from public.suppliers where code = 'mock'), (select id from public.products where sku = 'FIL-KAI-KEX'), 'MOCK-FIL-KAI-KEX', '5900000000671', 'Filtr powietrza do KAISAI Eco KEX (komplet)', 'KAISAI', 3900, 38, null, '{}'::jsonb),
  ((select id from public.suppliers where code = 'mock'), (select id from public.products where sku = 'PIL-KAI-UNI'), 'MOCK-PIL-KAI-UNI', '5900000000688', 'Pilot do klimatyzatora KAISAI (oryginalny)', 'KAISAI', 5900, 53, null, '{}'::jsonb),
  ((select id from public.suppliers where code = 'mock'), (select id from public.products where sku = 'CZU-TEMP-10K'), 'MOCK-CZU-TEMP-10K', '5900000000718', 'Czujnik temperatury NTC 10K uniwersalny', 'Rawicom', 2400, 1, null, '{}'::jsonb)
on conflict (supplier_id, supplier_sku) do update set purchase_net_cents = excluded.purchase_net_cents, stock = excluded.stock, lead_time_days = excluded.lead_time_days, product_id = excluded.product_id, fetched_at = now();

insert into public.product_mappings (supplier_id, supplier_sku, product_id, matched_by)
select o.supplier_id, o.supplier_sku, o.product_id, 'ean' from public.supplier_offers o where o.product_id is not null
on conflict (supplier_id, supplier_sku) do nothing;

-- --- Produkty powiązane (przykłady) ---
insert into public.product_relations (product_id, related_product_id, relation_type, position)
select p.id, r.id, 'accessory', row_number() over (partition by p.id)
from public.products p
join public.products r on r.sku in ('CU-SET-14-38', 'CU-14', 'CU-38', 'WSP-450', 'ASP-MINI-LIME', 'KAB-OMY-5x15')
where p.category_id = (select id from public.categories where slug = 'klimatyzatory-split')
on conflict do nothing;

insert into public.product_relations (product_id, related_product_id, relation_type, position)
select o.id, i.id, 'indoor_unit', 1
from public.products o join public.products i on i.sku = 'KAI-IN-WALL-26'
where o.sku in ('KAI-MULTI-2X', 'KAI-MULTI-3X')
on conflict do nothing;

-- --- Przeliczenie cen i stanów ---
select public.recalc_all_products();
